apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8smarch10am-5934"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8smarch10am-5934"
  template:
    metadata:
      labels:
        app: "k8smarch10am-5934"
    spec:
      containers:
        - name: "k8smarch10am-5934"
          image: "acrmarch10am.azurecr.io/k8smarch10am"
          ports:
          - containerPort: 80