apiVersion: v1
kind: Service
metadata:
    name: "k8smarch10am-5934"
    labels:
        app: "k8smarch10am-5934"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "k8smarch10am-5934"